// SPDX-License-Identifier: MIT
// Forked from: https://github.com/tornadocash/tornado-core/blob/master/contracts/MerkleTreeWithHistory.sol
// Changes from original:
//   1. Solidity ^0.7.0 -> ^0.8.21
//   2. IHasher (MiMC) removed; replaced with Poseidon2.hash() directly
//   3. ZERO_VALUE = 0 (empty leaf for Poseidon2 tree)
//   4. zeros() recomputed: zeros[i] = Poseidon2.hash(zeros[i-1], zeros[i-1])
//      Generated by test/Poseidon2IMT.t.sol::test_PrintZeroValues — DO NOT edit manually
//   5. ROOT_HISTORY_SIZE: 30 -> 100 (L2 high-throughput safety)
//   6. bytes32 -> uint256 (Poseidon2 field element compatibility)
// Insert algorithm, isKnownRoot do-while, filledSubtrees structure: UNCHANGED from TC original.
pragma solidity ^0.8.21;

import {Poseidon2} from "./Poseidon2.sol";

contract MerkleTreeWithHistory {

    uint256 public constant FIELD_SIZE =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    uint256 public constant ZERO_VALUE = 0;

    uint32 public levels;

    mapping(uint256 => uint256) public filledSubtrees;
    mapping(uint256 => uint256) public roots;

    uint32 public constant ROOT_HISTORY_SIZE = 100;
    uint32 public currentRootIndex = 0;
    uint32 public nextIndex = 0;

    constructor(uint32 _levels) {
        require(_levels > 0,  "_levels should be greater than zero");
        require(_levels < 32, "_levels should be less than 32");
        levels = _levels;
        for (uint32 i = 0; i < _levels; i++) {
            filledSubtrees[i] = zeros(i);
        }
        roots[0] = zeros(_levels - 1);
    }

    // Replaces TC hashLeftRight(IHasher, bytes32, bytes32)
    function hashLeftRight(uint256 _left, uint256 _right) public pure returns (uint256) {
        require(_left  < FIELD_SIZE, "_left should be inside the field");
        require(_right < FIELD_SIZE, "_right should be inside the field");
        return Poseidon2.hash(_left, _right);
    }

    // Identical insert algorithm to TC original. Only type changes.
    function _insert(uint256 _leaf) internal returns (uint32 index) {
        uint32 _nextIndex = nextIndex;
        require(
            _nextIndex != uint32(2) ** levels,
            "Merkle tree is full. No more leaves can be added"
        );
        uint32  currentIndex     = _nextIndex;
        uint256 currentLevelHash = _leaf;
        uint256 left;
        uint256 right;

        for (uint32 i = 0; i < levels; i++) {
            if (currentIndex % 2 == 0) {
                left  = currentLevelHash;
                right = zeros(i);
                filledSubtrees[i] = currentLevelHash;
            } else {
                left  = filledSubtrees[i];
                right = currentLevelHash;
            }
            currentLevelHash = hashLeftRight(left, right);
            currentIndex /= 2;
        }

        uint32 newRootIndex = (currentRootIndex + 1) % ROOT_HISTORY_SIZE;
        currentRootIndex = newRootIndex;
        roots[newRootIndex] = currentLevelHash;
        nextIndex = _nextIndex + 1;
        return _nextIndex;
    }

    // Identical to TC original — do-while is correct for ring buffer.
    // A for-loop has off-by-one when currentRootIndex == 0.
    function isKnownRoot(uint256 _root) public view returns (bool) {
        if (_root == 0) {
            return false;
        }
        uint32 _currentRootIndex = currentRootIndex;
        uint32 i = _currentRootIndex;
        do {
            if (_root == roots[i]) {
                return true;
            }
            if (i == 0) {
                i = ROOT_HISTORY_SIZE;
            }
            i--;
        } while (i != _currentRootIndex);
        return false;
    }

    function getLastRoot() public view returns (uint256) {
        return roots[currentRootIndex];
    }

    // zeros[i] = Poseidon2.hash(zeros[i-1], zeros[i-1])
    // zeros[0] = 0 (ZERO_VALUE)
    // Generated by test/Poseidon2IMT.t.sol::test_PrintZeroValues
    function zeros(uint256 i) public pure returns (uint256) {
        if (i == 0)  return 0x0000000000000000000000000000000000000000000000000000000000000000;
        if (i == 1)  return 0x18dfb8dc9b82229cff974efefc8df78b1ce96d9d844236b496785c698bc6732e;
        if (i == 2)  return 0x2c0d184fc7a25c124a27a67b2c46220b039b1a5072c3b693a18ffee458f6425d;
        if (i == 3)  return 0x268b2b93ac5fe540e618a378b8a71b8f2407232744d71e501ce8699980b306e5;
        if (i == 4)  return 0x2d436f654e14cc4febcafdf4a753b149dd8c88a75df9e5d6707e83a853b5f791;
        if (i == 5)  return 0x0b66fdef5a7f00f6fb45d1498b4d7131218e69ccf0a2751b6a1fb1bcd982867d;
        if (i == 6)  return 0x1d542b476c671bb6f0d2ab2939335d7cbad03476f1e3bcba70973b1adfe88b91;
        if (i == 7)  return 0x0680c6388c5798caf80642a1e84316b8b2f7caa99da076f3057d2962a46c5358;
        if (i == 8)  return 0x03c53ce5296e3e895171f89aa09f84214e3fb0755fe7a423b87888e4b3d731b8;
        if (i == 9)  return 0x2dd4e2510b33275359bba6edf72e6bdacad259950b024b2cc19d63c3a5b761df;
        if (i == 10) return 0x11cb221f69d954d521fb5393767e77fe4d14133757a706b318e62fa984f98157;
        if (i == 11) return 0x039d78bac8f890788eefe39af15eee5825056648f99210054fd03c25213f4de7;
        if (i == 12) return 0x0c55b828a83062a77d2b3e0a66bbb50cb6040990d9f368da8b24c0e82b692349;
        if (i == 13) return 0x24c866ac88715851268d808487e20e6986084fc222d7188e2a8e0f5b9f8457ef;
        if (i == 14) return 0x0f6a94e437b9dfb35cdedf41e2e154c3ae449b7c04c13add0996a7b53cde5400;
        if (i == 15) return 0x22afe7696b87cb782742e2d3ecb0f749a9beefbbb2159d178b09000e55b22cab;
        if (i == 16) return 0x121b01164d32e9ab841ba8f5602b0ec58b576e62552c96911d4d988d49468cdd;
        if (i == 17) return 0x05f3810707b1336c953b7db191215dab2b5772f93025aa345b954b43135b627b;
        if (i == 18) return 0x287515b2d5975c74e3fd85a20d68611a463ffe605a1c54d8140ab16d1b77f57b;
        if (i == 19) return 0x276ff13fde3afa1adb26149ddc3aa67240d603b6a91da5e494c8e58706381a38;
        if (i == 20) return 0x3039bcb20f03fd9c8650138ef2cfe643edeed152f9c20999f43aeed54d79e387;
        if (i == 21) return 0x087e5af439450ef09ce6f12a47571971d83309bb6fd1e280c29baf69257f8a4f;
        if (i == 22) return 0x1821495b1919fa5439ae4a314ff98843067381a3c015f744592bfd64101def1d;
        if (i == 23) return 0x25789f32f958568364c8139771d7864d93f97efb5bbb87cce1959e7e7443ac80;
        if (i == 24) return 0x25ad0850411551115fd697c4d91668f92dde52421be59650357cd50363880543;
        if (i == 25) return 0x10b604f35a902419a0fdcf8ee57123e92f0d650ab009b5105916cac7813c9137;
        if (i == 26) return 0x1bb07b96cdddee486afb20c78a3b82208cb80d2c55e596896fa1879164a751db;
        if (i == 27) return 0x04ab93e9c494b67162063e77960cd36f4e3e5cdee5388a603dc55a03875c72bb;
        if (i == 28) return 0x0f9e7f4ad948e7e487831c37fef6e032d66ab2cd3d742d024274612a86cc55ed;
        if (i == 29) return 0x2f1c6920644cd674376a6d3ba4fd3cbe3a571685af0d9ab28e1461e4c1d6fc0a;
        if (i == 30) return 0x0de2cd9dffe1e710647fdc179884bd0367276612ef83d2aeea0f7d8aecb9c3d7;
        if (i == 31) return 0x0077ed17dad4b561a9b4a21cf58720ef0c057699fec72b92f2ca26fdf6b48a83;
        revert("Index out of bounds");
    }
}
