// SPDX-License-Identifier: MIT
// Incremental Merkle Tree using Poseidon2 (Barretenberg BN254 t=4)
//
// Forked pattern from: tornado-cash/tornado-core/contracts/MerkleTreeWithHistory.sol
// Hash function: Poseidon2.sol (translated from Aztec/Barretenberg poseidon2_params.hpp)
//
// Architecture: Fixed depth 20, left-to-right insertion, zero-padded empty leaves.
// This MUST match the Merkle tree logic in main.nr exactly.
//
// INVARIANT: _root() == Noir circuit root for the same inserted leaves.
// Verified by test/Poseidon2IMT.t.sol.

pragma solidity ^0.8.21;

import {Poseidon2} from "./Poseidon2.sol";

library Poseidon2IMT {

    uint256 internal constant DEPTH     = 20;
    uint256 internal constant MAX_LEAVES = 1 << DEPTH; // 1,048,576
    uint256 internal constant ROOT_HISTORY_SIZE = 30;

    struct IMTData {
        uint256 size;
        uint256[DEPTH] filledSubtrees;
        uint256[ROOT_HISTORY_SIZE] roots;
        uint256 currentRootIndex;
    }

    // -------------------------------------------------------------------------
    // Zero values: zeros[i] = Poseidon2.hash(zeros[i-1], zeros[i-1])
    // zeros[0] = 0 (empty leaf value)
    // Generated by test/Poseidon2IMT.t.sol::test_PrintZeroValues — DO NOT edit manually.
    // -------------------------------------------------------------------------
    function _zeros(uint256 i) internal pure returns (uint256) {
        if (i == 0)  return 0x0000000000000000000000000000000000000000000000000000000000000000;
        if (i == 1)  return 0x18dfb8dc9b82229cff974efefc8df78b1ce96d9d844236b496785c698bc6732e;
        if (i == 2)  return 0x2c0d184fc7a25c124a27a67b2c46220b039b1a5072c3b693a18ffee458f6425d;
        if (i == 3)  return 0x268b2b93ac5fe540e618a378b8a71b8f2407232744d71e501ce8699980b306e5;
        if (i == 4)  return 0x2d436f654e14cc4febcafdf4a753b149dd8c88a75df9e5d6707e83a853b5f791;
        if (i == 5)  return 0x0b66fdef5a7f00f6fb45d1498b4d7131218e69ccf0a2751b6a1fb1bcd982867d;
        if (i == 6)  return 0x1d542b476c671bb6f0d2ab2939335d7cbad03476f1e3bcba70973b1adfe88b91;
        if (i == 7)  return 0x0680c6388c5798caf80642a1e84316b8b2f7caa99da076f3057d2962a46c5358;
        if (i == 8)  return 0x03c53ce5296e3e895171f89aa09f84214e3fb0755fe7a423b87888e4b3d731b8;
        if (i == 9)  return 0x2dd4e2510b33275359bba6edf72e6bdacad259950b024b2cc19d63c3a5b761df;
        if (i == 10) return 0x11cb221f69d954d521fb5393767e77fe4d14133757a706b318e62fa984f98157;
        if (i == 11) return 0x039d78bac8f890788eefe39af15eee5825056648f99210054fd03c25213f4de7;
        if (i == 12) return 0x0c55b828a83062a77d2b3e0a66bbb50cb6040990d9f368da8b24c0e82b692349;
        if (i == 13) return 0x24c866ac88715851268d808487e20e6986084fc222d7188e2a8e0f5b9f8457ef;
        if (i == 14) return 0x0f6a94e437b9dfb35cdedf41e2e154c3ae449b7c04c13add0996a7b53cde5400;
        if (i == 15) return 0x22afe7696b87cb782742e2d3ecb0f749a9beefbbb2159d178b09000e55b22cab;
        if (i == 16) return 0x121b01164d32e9ab841ba8f5602b0ec58b576e62552c96911d4d988d49468cdd;
        if (i == 17) return 0x05f3810707b1336c953b7db191215dab2b5772f93025aa345b954b43135b627b;
        if (i == 18) return 0x287515b2d5975c74e3fd85a20d68611a463ffe605a1c54d8140ab16d1b77f57b;
        if (i == 19) return 0x276ff13fde3afa1adb26149ddc3aa67240d603b6a91da5e494c8e58706381a38;
        if (i == 20) return 0x3039bcb20f03fd9c8650138ef2cfe643edeed152f9c20999f43aeed54d79e387;
        revert("Poseidon2IMT: depth out of range");
    }

    // -------------------------------------------------------------------------
    // Init — call once at construction
    // -------------------------------------------------------------------------
    function _init(IMTData storage self) internal {
        for (uint256 i = 0; i < DEPTH; i++) {
            self.filledSubtrees[i] = _zeros(i);
        }
        self.roots[0] = _zeros(DEPTH);
        self.currentRootIndex = 0;
        self.size = 0;
    }

    // -------------------------------------------------------------------------
    // Insert a leaf. Returns the leaf index.
    // -------------------------------------------------------------------------
    function _insert(IMTData storage self, uint256 leaf) internal returns (uint256 index) {
        require(self.size < MAX_LEAVES, "Poseidon2IMT: tree full");

        index = self.size;
        uint256 currentIndex = index;
        uint256 currentHash  = leaf;

        for (uint256 i = 0; i < DEPTH; i++) {
            uint256 left;
            uint256 right;

            if (currentIndex % 2 == 0) {
                // leaf is left child — right sibling is a zero subtree
                left  = currentHash;
                right = _zeros(i);
                // cache this node so future right siblings can use it
                self.filledSubtrees[i] = currentHash;
            } else {
                // leaf is right child — left sibling was cached
                left  = self.filledSubtrees[i];
                right = currentHash;
            }

            currentHash   = Poseidon2.hash(left, right);
            currentIndex >>= 1;
        }

        // Store root in ring buffer
        uint256 newRootIndex = (self.currentRootIndex + 1) % ROOT_HISTORY_SIZE;
        self.currentRootIndex       = newRootIndex;
        self.roots[newRootIndex]    = currentHash;
        self.size++;
    }

    // -------------------------------------------------------------------------
    // Views
    // -------------------------------------------------------------------------

    function _root(IMTData storage self) internal view returns (uint256) {
        return self.roots[self.currentRootIndex];
    }

    /// @notice Returns true if root is in the last ROOT_HISTORY_SIZE roots.
    function _isKnownRoot(IMTData storage self, uint256 root) internal view returns (bool) {
        if (root == 0) return false;
        uint256 i = self.currentRootIndex;
        for (uint256 j = 0; j < ROOT_HISTORY_SIZE; j++) {
            if (self.roots[i] == root) return true;
            i = (i == 0) ? ROOT_HISTORY_SIZE - 1 : i - 1;
        }
        return false;
    }

    /// @notice O(n) leaf existence check. Only use off-chain or in tests.
    function _has(IMTData storage /*self*/, uint256 /*leaf*/) internal pure returns (bool) {
        // LeanIMT compatibility shim — vault calls this before insert
        // We track via a separate mapping in the vault, not here.
        // This function intentionally always returns false;
        // duplicate prevention is handled by the vault's commitmentExists mapping.
        return false;
    }
}
