// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import {Script, console} from "forge-std/Script.sol";
import {NofaceVault} from "../contracts/src/core/NofaceVault.sol";
import {ERC20} from "@openzeppelin/contracts/token/ERC20/ERC20.sol";

// Mock USDC for testnet only -- replace with real USDC address on mainnet
contract TestUSDC is ERC20 {
    constructor() ERC20("USD Coin", "USDC") {
        _mint(msg.sender, 10_000_000 * 1e6);
    }
    function decimals() public pure override returns (uint8) { return 6; }
}

// Generated by Barretenberg from the real circuit VK -- do NOT modify
interface IHonkVerifier {
    function verify(bytes calldata proof, bytes32[] calldata publicInputs) external view returns (bool);
}

contract DeployNoface is Script {
    function run() external {
        uint256 deployerKey = vm.envUint("PRIVATE_KEY");
        address deployer    = vm.addr(deployerKey);

        console.log("Deploying from:", deployer);

        vm.startBroadcast(deployerKey);

        // Testnet only -- swap for real USDC on mainnet
        TestUSDC usdc = new TestUSDC();
        console.log("MockUSDC deployed:    ", address(usdc));

        // Real UltraHonk verifier generated from main.nr VK
        // Source: circuits/target/HonkVerifier.sol
        // VK_HASH: 0x18fedb63ef8554a9d6a700bbd07a84266b9953b2d63a9f6f93d4521b16764689
        bytes memory verifierBytecode = type(HonkVerifier).creationCode;
        address verifierAddr;
        assembly {
            verifierAddr := create(0, add(verifierBytecode, 0x20), mload(verifierBytecode))
        }
        require(verifierAddr != address(0), "Verifier deploy failed");
        console.log("HonkVerifier deployed:", verifierAddr);

        NofaceVault vault = new NofaceVault(
            address(usdc),
            verifierAddr
        );
        console.log("NofaceVault deployed: ", address(vault));

        vm.stopBroadcast();

        console.log("---");
        console.log("NOFACE Deployment Complete");
        console.log("USDC:     ", address(usdc));
        console.log("Verifier: ", verifierAddr);
        console.log("Vault:    ", address(vault));
    }
}

// Import the real verifier so the compiler includes it
import {HonkVerifier} from "../contracts/src/core/HonkVerifier.sol";
