// SPDX-License-Identifier: MIT
// Forked from: https://github.com/tornadocash/tornado-core/blob/master/contracts/Tornado.sol
// Changes from original:
//   1. Solidity ^0.7.0 -> ^0.8.23
//   2. IVerifier (Groth16, uint256[6]) -> IHonkVerifier (Noir/UltraHonk, bytes32[] publicInputs)
//   3. IHasher (MiMC) removed — tree uses Poseidon2 natively (see MerkleTreeWithHistory.sol)
//   4. Multi-denomination support: DENOM_SMALL / MEDIUM / LARGE (fixed set like TC instances)
//   5. Safety modules added (CTO Spec V2):
//      - Deposit caps (TVL limit for guarded launch)
//      - Guardian multisig (3-of-5) with pause functionality
//      - Emergency withdrawal controls
//   6. _refund parameter removed (no ETH rebate; ERC20 only).
//   7. Intent binding: recipient, relayer, fee are public circuit inputs — proof is cryptographically
//      bound to them so no actor can tamper with or front-run an in-flight withdrawal.
//
// Threat model:
//   GUARANTEED by cryptography:
//     - Deposit/withdrawal link is broken (nullifier scheme).
//     - Proof binds recipient, relayer, fee — no substitution possible.
//   ASSUMED (trust in relayer):
//     - Relayer may soft-censor by refusing to submit. Mitigation: system is permissionless;
//       user can self-relay or use any other relayer.
//   RESIDUAL RISK:
//     - Long-term behaviour clustering. Mitigation: enforced denomination buckets maximise anonymity set.
pragma solidity ^0.8.23;

import {MerkleTreeWithHistory} from "./MerkleTreeWithHistory.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/// @dev Adapter to our Noir/UltraHonk verifier generated by `bb`.
interface IHonkVerifier {
    function verify(bytes calldata proof, bytes32[] calldata publicInputs) external view returns (bool);
}

/// @title  VeilCore
/// @notice Abstract privacy primitive. Forked from tornado-core's Tornado.sol.
///         Deposit commits a leaf into the Merkle tree. Withdrawal requires a
///         valid ZK proof that the caller knows the secret opening a committed leaf,
///         without revealing WHICH leaf. Denomination enforced in both proof circuit
///         and contract to prevent cross-pool double-spend.
abstract contract VeilCore is MerkleTreeWithHistory, ReentrancyGuard, Ownable {

    // ── Fixed denominations — maximise anonymity set across users ─────────────
    uint256 public constant DENOM_SMALL  = 100   * 1e6;  // 100  USDC
    uint256 public constant DENOM_MEDIUM = 1_000 * 1e6;  // 1000 USDC
    uint256 public constant DENOM_LARGE  = 10_000 * 1e6; // 10k  USDC

    uint256 public constant SNARK_SCALAR_FIELD =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    IHonkVerifier public immutable verifier;

    mapping(bytes32 => bool) public commitments;
    mapping(bytes32 => bool) public nullifierHashes;
    
    // ── Safety Modules (CTO Spec V2) ──────────────────────────────────────────
    // Guarded Launch: Deposit cap for first 90 days
    uint256 public depositCap;              // Max TVL (e.g., 500k USDC)
    uint256 public currentTVL;              // Current total value locked
    uint256 public launchStartTime;         // When deposits were first enabled
    uint256 public constant GUARDED_PERIOD = 90 days; // Guarded launch duration
    
    // Emergency controls
    bool public paused;                   // Emergency pause
    bool public withdrawPaused;           // Separate pause for withdrawals
    address public guardian;              // 3-of-5 multisig address
    
    // ── Events ─────────────────────────────────────────────────────────────────
    event Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp);
    event Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee);
    event DepositCapUpdated(uint256 newCap);
    event GuardianUpdated(address newGuardian);
    event EmergencyPause(bool depositsPaused, bool withdrawsPaused);

    // ── Errors ─────────────────────────────────────────────────────────────────
    error InvalidDenomination();
    error CommitmentAlreadyExists();
    error CommitmentOutOfField();
    error InvalidRoot();
    error NullifierAlreadySpent();
    error ProofVerificationFailed();
    error FeeTooHigh();
    error ZeroRecipient();
    error DepositCapExceeded();
    error GuardedLaunchExpired();
    error Paused();
    error WithdrawPaused();
    error InvalidGuardian();
    error Unauthorized();
    
    // ── Modifiers ─────────────────────────────────────────────────────────────
    modifier whenNotPaused() {
        if (paused) revert Paused();
        _;
    }
    
    modifier whenWithdrawNotPaused() {
        if (withdrawPaused) revert WithdrawPaused();
        _;
    }
    
    modifier onlyGuardian() {
        if (msg.sender != guardian && msg.sender != owner()) revert InvalidGuardian();
        _;
    }
    
    modifier checkDepositCap(uint256 amount) {
        // Only enforce cap during guarded launch period
        if (block.timestamp < launchStartTime + GUARDED_PERIOD) {
            if (currentTVL + amount > depositCap) revert DepositCapExceeded();
        }
        _;
    }

    constructor(address _verifier, uint256 _depositCap) MerkleTreeWithHistory(20) Ownable(msg.sender) {
        verifier = IHonkVerifier(_verifier);
        depositCap = _depositCap;
        launchStartTime = block.timestamp;
        // Default guardian is owner (can be changed to multisig)
        guardian = msg.sender;
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Deposit
    // ─────────────────────────────────────────────────────────────────────────

    /// @notice Deposit `denomination` tokens. The caller must have pre-approved the contract.
    /// @param  commitment   Poseidon2(secret, nullifier, denomination, 0) — computed client-side.
    /// @param  denomination Must be one of the three fixed denominations.
    function deposit(bytes32 commitment, uint256 denomination) 
        external 
        nonReentrant 
        whenNotPaused
        checkDepositCap(denomination)
    {
        if (denomination != DENOM_SMALL &&
            denomination != DENOM_MEDIUM &&
            denomination != DENOM_LARGE)   revert InvalidDenomination();
        if (uint256(commitment) >= SNARK_SCALAR_FIELD) revert CommitmentOutOfField();
        if (commitments[commitment])                    revert CommitmentAlreadyExists();

        commitments[commitment] = true;
        uint32 leafIndex = _insert(uint256(commitment));
        
        // Update TVL tracking
        currentTVL += denomination;
        
        _processDeposit(denomination);

        emit Deposit(commitment, leafIndex, block.timestamp);
    }

    /// @dev Implemented by concrete child to handle the token transfer.
    function _processDeposit(uint256 denomination) internal virtual;

    // ─────────────────────────────────────────────────────────────────────────
    // Withdraw
    // ─────────────────────────────────────────────────────────────────────────

    /// @notice Withdraw a deposit. Requires a valid Noir/UltraHonk ZK proof.
    ///
    /// @param  proof         Raw UltraHonk proof bytes from `bb prove`.
    /// @param  root          A known Merkle root (within ROOT_HISTORY_SIZE history).
    /// @param  nullifierHash Poseidon2(nullifier, commitment, 0, 0) — prevents double-spend.
    /// @param  recipient     Recipient of the funds. Bound in proof — cannot be swapped.
    /// @param  denomination  Must match the denomination committed to in the proof circuit.
    /// @param  relayer       Address to receive `fee`. Set to address(0) for self-relay.
    /// @param  fee           Relayer fee in token units. Bound in proof — cannot be inflated.
    ///
    /// Public inputs (must match circuit src/kernel/main.nr):
    ///   [0] nullifierHash
    ///   [1] root
    ///   [2] recipient (address as Field)
    ///   [3] denomination
    ///   [4] relayer   (address as Field)
    ///   [5] fee
    function withdraw(
        bytes calldata proof,
        bytes32 root,
        bytes32 nullifierHash,
        address recipient,
        uint256 denomination,
        address relayer,
        uint256 fee
    ) external nonReentrant whenWithdrawNotPaused {
        if (recipient == address(0))              revert ZeroRecipient();
        if (!isKnownRoot(uint256(root)))          revert InvalidRoot();
        if (nullifierHashes[nullifierHash])        revert NullifierAlreadySpent();
        if (denomination != DENOM_SMALL &&
            denomination != DENOM_MEDIUM &&
            denomination != DENOM_LARGE)          revert InvalidDenomination();
        if (fee >= denomination)                   revert FeeTooHigh();

        // Build public inputs exactly as the circuit expects.
        bytes32[] memory publicInputs = new bytes32[](6);
        publicInputs[0] = nullifierHash;
        publicInputs[1] = root;
        publicInputs[2] = bytes32(uint256(uint160(recipient)));
        publicInputs[3] = bytes32(denomination);
        publicInputs[4] = bytes32(uint256(uint160(relayer)));
        publicInputs[5] = bytes32(fee);

        bool ok;
        try verifier.verify(proof, publicInputs) returns (bool result) {
            ok = result;
        } catch {
            revert ProofVerificationFailed();
        }
        if (!ok) revert ProofVerificationFailed();

        nullifierHashes[nullifierHash] = true;
        
        // Update TVL tracking
        currentTVL -= denomination;
        
        _processWithdraw(payable(recipient), payable(relayer), denomination, fee);

        emit Withdrawal(recipient, nullifierHash, relayer, fee);
    }

    /// @dev Implemented by concrete child to handle the token transfer.
    function _processWithdraw(
        address payable recipient,
        address payable relayer,
        uint256 denomination,
        uint256 fee
    ) internal virtual;

    // ─────────────────────────────────────────────────────────────────────────
    // View helpers (identical to TC original)
    // ─────────────────────────────────────────────────────────────────────────

    function isSpent(bytes32 _nullifierHash) external view returns (bool) {
        return nullifierHashes[_nullifierHash];
    }

    function isSpentArray(bytes32[] calldata _nullifierHashes) external view returns (bool[] memory spent) {
        spent = new bool[](_nullifierHashes.length);
        for (uint256 i = 0; i < _nullifierHashes.length; i++) {
            spent[i] = nullifierHashes[_nullifierHashes[i]];
        }
    }

    function getRoot() external view returns (bytes32) {
        return bytes32(getLastRoot());
    }

    function getLeafCount() external view returns (uint256) {
        return nextIndex;
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Safety Module Admin Functions (CTO Spec V2)
    // ─────────────────────────────────────────────────────────────────────────
    
    /// @notice Update the deposit cap. Only owner during guarded launch.
    /// @param _newCap The new maximum TVL allowed during guarded launch
    function updateDepositCap(uint256 _newCap) external onlyOwner {
        depositCap = _newCap;
        emit DepositCapUpdated(_newCap);
    }
    
    /// @notice Set the guardian address (should be 3-of-5 multisig). Only owner.
    /// @param _guardian The address of the guardian multisig
    function setGuardian(address _guardian) external onlyOwner {
        if (_guardian == address(0)) revert InvalidGuardian();
        guardian = _guardian;
        emit GuardianUpdated(_guardian);
    }
    
    /// @notice Emergency pause deposits. Guardian or owner can call.
    function pauseDeposits() external onlyGuardian {
        paused = true;
        emit EmergencyPause(true, withdrawPaused);
    }
    
    /// @notice Emergency pause withdrawals. Guardian can call (owner requires higher authority).
    /// @dev Only guardian can pause withdrawals; owner can only unpause.
    function pauseWithdrawals() external onlyGuardian {
        withdrawPaused = true;
        emit EmergencyPause(paused, true);
    }
    
    /// @notice Unpause deposits. Only owner.
    function unpauseDeposits() external onlyOwner {
        paused = false;
        emit EmergencyPause(false, withdrawPaused);
    }
    
    /// @notice Unpause withdrawals. Only owner.
    function unpauseWithdrawals() external onlyOwner {
        withdrawPaused = false;
        emit EmergencyPause(paused, false);
    }
    
    /// @notice Emergency function to update TVL in case of accounting mismatch.
    /// @dev Only guardian can call in emergency situations.
    function emergencyUpdateTVL(uint256 _newTVL) external onlyGuardian {
        currentTVL = _newTVL;
    }
    
    /// @notice Check if guarded launch period is still active
    function isGuardedLaunchActive() external view returns (bool) {
        return block.timestamp < launchStartTime + GUARDED_PERIOD;
    }
    
    /// @notice Get remaining capacity in the vault
    function remainingCapacity() external view returns (uint256) {
        if (block.timestamp >= launchStartTime + GUARDED_PERIOD) {
            return type(uint256).max; // No cap after guarded launch
        }
        if (currentTVL >= depositCap) return 0;
        return depositCap - currentTVL;
    }
}
