// SPDX-License-Identifier: MIT
// Forked from: https://github.com/tornadocash/tornado-core/blob/master/contracts/Tornado.sol
// Changes from original:
//   1. Solidity ^0.7.0 -> ^0.8.23
//   2. IVerifier (Groth16, uint256[6]) -> IHonkVerifier (Noir/UltraHonk, bytes32[] publicInputs)
//   3. IHasher (MiMC) removed — tree uses Poseidon2 natively (see MerkleTreeWithHistory.sol)
//   4. Multi-denomination support: DENOM_SMALL / MEDIUM / LARGE (fixed set like TC instances)
//   5. All fees and tokenomics removed — pure privacy primitive only.
//   6. _refund parameter removed (no ETH rebate; ERC20 only).
//   7. Intent binding: recipient, relayer, fee are public circuit inputs — proof is cryptographically
//      bound to them so no actor can tamper with or front-run an in-flight withdrawal.
//
// Threat model:
//   GUARANTEED by cryptography:
//     - Deposit/withdrawal link is broken (nullifier scheme).
//     - Proof binds recipient, relayer, fee — no substitution possible.
//   ASSUMED (trust in relayer):
//     - Relayer may soft-censor by refusing to submit. Mitigation: system is permissionless;
//       user can self-relay or use any other relayer.
//   RESIDUAL RISK:
//     - Long-term behaviour clustering. Mitigation: enforced denomination buckets maximise anonymity set.
pragma solidity ^0.8.23;

import {MerkleTreeWithHistory} from "./MerkleTreeWithHistory.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

/// @dev Adapter to our Noir/UltraHonk verifier generated by `bb`.
interface IHonkVerifier {
    function verify(bytes calldata proof, bytes32[] calldata publicInputs) external view returns (bool);
}

/// @title  VeilCore
/// @notice Abstract privacy primitive. Forked from tornado-core's Tornado.sol.
///         Deposit commits a leaf into the Merkle tree. Withdrawal requires a
///         valid ZK proof that the caller knows the secret opening a committed leaf,
///         without revealing WHICH leaf. Denomination enforced in both proof circuit
///         and contract to prevent cross-pool double-spend.
abstract contract VeilCore is MerkleTreeWithHistory, ReentrancyGuard {

    // ── Fixed denominations — maximise anonymity set across users ─────────────
    uint256 public constant DENOM_SMALL  = 100   * 1e6;  // 100  USDC
    uint256 public constant DENOM_MEDIUM = 1_000 * 1e6;  // 1000 USDC
    uint256 public constant DENOM_LARGE  = 10_000 * 1e6; // 10k  USDC

    uint256 public constant SNARK_SCALAR_FIELD =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    IHonkVerifier public immutable verifier;

    mapping(bytes32 => bool) public commitments;
    mapping(bytes32 => bool) public nullifierHashes;

    // ── Events ─────────────────────────────────────────────────────────────────
    event Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp);
    event Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee);

    // ── Errors ─────────────────────────────────────────────────────────────────
    error InvalidDenomination();
    error CommitmentAlreadyExists();
    error CommitmentOutOfField();
    error InvalidRoot();
    error NullifierAlreadySpent();
    error ProofVerificationFailed();
    error FeeTooHigh();
    error ZeroRecipient();

    constructor(address _verifier) MerkleTreeWithHistory(20) {
        verifier = IHonkVerifier(_verifier);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Deposit
    // ─────────────────────────────────────────────────────────────────────────

    /// @notice Deposit `denomination` tokens. The caller must have pre-approved the contract.
    /// @param  commitment   Poseidon2(secret, nullifier, denomination, 0) — computed client-side.
    /// @param  denomination Must be one of the three fixed denominations.
    function deposit(bytes32 commitment, uint256 denomination) external nonReentrant {
        if (denomination != DENOM_SMALL &&
            denomination != DENOM_MEDIUM &&
            denomination != DENOM_LARGE)   revert InvalidDenomination();
        if (uint256(commitment) >= SNARK_SCALAR_FIELD) revert CommitmentOutOfField();
        if (commitments[commitment])                    revert CommitmentAlreadyExists();

        commitments[commitment] = true;
        uint32 leafIndex = _insert(uint256(commitment));
        _processDeposit(denomination);

        emit Deposit(commitment, leafIndex, block.timestamp);
    }

    /// @dev Implemented by concrete child to handle the token transfer.
    function _processDeposit(uint256 denomination) internal virtual;

    // ─────────────────────────────────────────────────────────────────────────
    // Withdraw
    // ─────────────────────────────────────────────────────────────────────────

    /// @notice Withdraw a deposit. Requires a valid Noir/UltraHonk ZK proof.
    ///
    /// @param  proof         Raw UltraHonk proof bytes from `bb prove`.
    /// @param  root          A known Merkle root (within ROOT_HISTORY_SIZE history).
    /// @param  nullifierHash Poseidon2(nullifier, commitment, 0, 0) — prevents double-spend.
    /// @param  recipient     Recipient of the funds. Bound in proof — cannot be swapped.
    /// @param  denomination  Must match the denomination committed to in the proof circuit.
    /// @param  relayer       Address to receive `fee`. Set to address(0) for self-relay.
    /// @param  fee           Relayer fee in token units. Bound in proof — cannot be inflated.
    ///
    /// Public inputs (must match circuit src/kernel/main.nr):
    ///   [0] nullifierHash
    ///   [1] root
    ///   [2] recipient (address as Field)
    ///   [3] denomination
    ///   [4] relayer   (address as Field)
    ///   [5] fee
    function withdraw(
        bytes calldata proof,
        bytes32 root,
        bytes32 nullifierHash,
        address recipient,
        uint256 denomination,
        address relayer,
        uint256 fee
    ) external nonReentrant {
        if (recipient == address(0))              revert ZeroRecipient();
        if (!isKnownRoot(uint256(root)))          revert InvalidRoot();
        if (nullifierHashes[nullifierHash])        revert NullifierAlreadySpent();
        if (denomination != DENOM_SMALL &&
            denomination != DENOM_MEDIUM &&
            denomination != DENOM_LARGE)          revert InvalidDenomination();
        if (fee >= denomination)                   revert FeeTooHigh();

        // Build public inputs exactly as the circuit expects.
        bytes32[] memory publicInputs = new bytes32[](6);
        publicInputs[0] = nullifierHash;
        publicInputs[1] = root;
        publicInputs[2] = bytes32(uint256(uint160(recipient)));
        publicInputs[3] = bytes32(denomination);
        publicInputs[4] = bytes32(uint256(uint160(relayer)));
        publicInputs[5] = bytes32(fee);

        bool ok;
        try verifier.verify(proof, publicInputs) returns (bool result) {
            ok = result;
        } catch {
            revert ProofVerificationFailed();
        }
        if (!ok) revert ProofVerificationFailed();

        nullifierHashes[nullifierHash] = true;
        _processWithdraw(payable(recipient), payable(relayer), denomination, fee);

        emit Withdrawal(recipient, nullifierHash, relayer, fee);
    }

    /// @dev Implemented by concrete child to handle the token transfer.
    function _processWithdraw(
        address payable recipient,
        address payable relayer,
        uint256 denomination,
        uint256 fee
    ) internal virtual;

    // ─────────────────────────────────────────────────────────────────────────
    // View helpers (identical to TC original)
    // ─────────────────────────────────────────────────────────────────────────

    function isSpent(bytes32 _nullifierHash) external view returns (bool) {
        return nullifierHashes[_nullifierHash];
    }

    function isSpentArray(bytes32[] calldata _nullifierHashes) external view returns (bool[] memory spent) {
        spent = new bool[](_nullifierHashes.length);
        for (uint256 i = 0; i < _nullifierHashes.length; i++) {
            spent[i] = nullifierHashes[_nullifierHashes[i]];
        }
    }

    function getRoot() external view returns (bytes32) {
        return bytes32(getLastRoot());
    }

    function getLeafCount() external view returns (uint256) {
        return nextIndex;
    }
}
