[workspace]
members = ["kernel", "swap", "transfer", "clean_set", "bet"]

[[package]]
name = "noface_kernel"
type = "bin"
authors = ["VeilFi Protocol"]
entry = "src/kernel/main.nr"

[[package]]
name = "swap"
type = "bin"
authors = ["VeilFi Protocol"]
entry = "src/apps/swap.nr"

[[package]]
name = "transfer"
type = "bin"
authors = ["VeilFi Protocol"]
entry = "src/apps/transfer.nr"

[[package]]
name = "clean_set"
type = "bin"
authors = ["VeilFi Protocol"]
entry = "src/apps/clean_set.nr"

[[package]]
name = "bet"
type = "bin"
authors = ["VeilFi Protocol"]
entry = "src/apps/bet.nr"

[dependencies]
